[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "software-interview-cfd-workflow"
version = "0.1.0"
description = "A CFD Workflow."
authors = [
    { name = "Davis Balgley", email = "davis.balgley@gmail.com" }
]
readme = "INSTRUCTIONS.md"
requires-python = ">=3.8"
license = { text = "MIT" }
dependencies = [
    "tqdm>=4.68",
]

[project.scripts]
cfd-pipeline = "cfd_pipeline.cli:main"

# Optional dependency lists. Installed using [].
# For example, pip install -e .[dev], or pip install example_project[test]
[project.optional-dependencies]
dev = [
    "ruff",
    "pytest>=8",
    "pytest-cov>=5",
    "pre-commit>=3.5",
    "mypy==1.11.1",
  ]
test = ["pytest"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

# Pytest Configuration
[tool.pytest.ini_options]
# ensure pytest can locate the project's source code
pythonpath = [
  "src",
]
# End Pytest Configuration

# Ruff Configuration
[tool.ruff]
exclude = ["bin"]
extend-exclude = ["bin"]
# avoid automatically removing unused imports in __init__.py files
ignore-init-module-imports = true
# enable and enforce pydocstyle checks, default ruff checks and isort
lint.select = [
  # Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
  # Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
  # McCabe complexity (`C901`) by default.
  "E4",
  "E7",
  "E9",
  "E501",
  "F",
  "D", # pydocstyle
  "I", # isort
]
pydocstyle.convention = "numpy"
# don't require docstrings in public modules
lint.ignore = [
  "D100",
  "D104",
]
# End Ruff Configuration

# Mypy Configuration
[tool.mypy]
strict = true
pretty = true
exclude = ["^bin/"]
# End Mypy Configuration
